micronaut:
  application:
    name: mdataProbe
  metrics:
    export:
      datadog:
        enabled: true
        apiKey: ${DATADOG_APIKEY}
        step: PT1M
    enabled: true
datasources:
  default:
    url: jdbc:sqlserver://localhost:1433;databaseName=tempdb
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
